site_name: Snowboard Kindi
site_url: https://koeningerdigital.github.io/snowboard_kindi/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md

theme:
    name: 'material'
    palette:
        primary: custom
    language: de
    icon:
      logo: images/logo_snowboardkidis.png
      repo: fontawesome/brands/github
    features:
      - navigation.tabs
      - navigation.sections
      - toc.integrate
      - navigation.top
      - search.suggest
      - search.highlight
      - content.tabs.link

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/matomo.js

repo_name: 'koeningerdigital/snowboard_kindi'
repo_url: 'https://github.com/koeningerdigital/snowboard_kindi'

extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/'
        - icon: fontawesome/brands/github
          link: 'https://github.com/'
    giscus: true
    generator: false

copyright: https://github.com/koeningerdigital/

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - rss:
      abstract_chars_count: -1  # -1 for full content
